#!/bin/bash
usage()
{
  echo "Usage: $0 <URL> -c <nThreads>";
  exit 2;
}

if [ "$#" -ne 3 ]; then
    echo "Illegal number of parameters";
    usage
fi

if [ "$2" != "-c" ]; then
    echo "Wrong parameter given in 2nd position";
    usage
fi

source venv/bin/activate
python3 downloader.py $1 $3
deactivate